
name = "riskxlabs-box-cloudflare"
main = "src/worker.js"
compatibility_date = "2025-01-13"

[assets]
directory = "./docs"
binding = "ASSETS"

[[d1_databases]]
binding = "BOX_DB"
database_name = "riskxlabs_box_db"
database_id = "e9de5049-47d1-4a52-9748-810dbc8fbe94"
